'''
Every elliptic curve point in a cyclic group has a “number”

- A cyclic group can be generated by repeatedly applying the binary operator to the generator element. 

Since point addition over a finite field turns elliptic curve points into a cyclic group,
-> there exists at a generator element. 
-> each elliptic curve 

Let’s use a real example of y² = x³ + 3 (mod 11) with the generator point being (4, 10).

Using the python functions above, we can start with the point (4, 10) and generate every point in the group


'''